-- 계정 생성
CREATE USER c##SERVER IDENTIFIED BY SERVER;

-- 권한 부여
GRANT CONNECT, RESOURCE TO c##SERVER;

-- 테이블 스페이스 설정
ALTER USER C##SERVER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

drop user c##server;






-- 계정 생성
CREATE USER c##JDBC IDENTIFIED BY JDBC;

-- 권한 부여
GRANT CONNECT, RESOURCE TO c##JDBC;

-- 테이블 스페이스 설정
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

drop user c##server;
