-- 계정 생성
CREATE USER c##REVIEW IDENTIFIED BY REVIEW;

-- 권한 부여
GRANT CONNECT, RESOURCE TO c##REVIEW;

-- 테이블 스페이스 설정
ALTER USER C##REVIEW DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP TABLE TEST;

CREATE TABLE TEST(
    TNO NUMBER PRIMARY KEY,
    TNAME VARCHAR2(100) NOT NULL,
    TDATE DATE DEFAULT SYSDATE NOT NULL
);

select * from test;


--1)컬럼 추가/수정/삭제
--DEPARTMENT에 CNAME컬럼을 추가
ALTER TABLE DEPARTMENT ADD CNAME VARCHAR2(20);

--LNAME컬럼 추가 -> 기본값 '한국'
ALTER TABLE DEPARTMENT ADD LNAME VARCHAR2(20) DEFAULT '한국';
SELECT * FROM DEPARTMENT;

--1_2)컬럼 수정
--데이터타입 수정 : MODIFY 컬럼명 변경하고자하는 데이터타입
ALTER TABLE DEPARTMENT MODIFY CNAME VARCHAR2(30);
ALTER TABLE DEPARTMENT MODIFY LNAME NUMBER; --형식오류 발생

--DEFAULT값 수정 : MODIFY 컬럼명 DEFAULT 변경할 기본값
--LNAME컬럼의 DEFAULT '미국'으로 변경
ALTER TABLE DEPARTMENT MODIFY LNAME DEFAULT '미국';


